name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  sonar:
    runs-on: self-hosted

    steps:

      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4


      # 2. Setup Java (required)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      # 3. Download SonarScanner (Windows runner)
      - name: Download SonarScanner
        shell: powershell
        run: |
          Invoke-WebRequest https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip -OutFile scanner.zip
          Expand-Archive scanner.zip -DestinationPath .
          Rename-Item sonar-scanner-5.0.1.3006-windows sonar-scanner


      # 4. Run scan → SonarQube in EC2 Ubuntu
      - name: Run SonarQube Scan
        shell: powershell
        run: |
          cmd /c sonar-scanner\bin\sonar-scanner.bat -Dsonar.projectKey=student-project -Dsonar.sources=. -Dsonar.host.url=http://18.212.15.84:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }}
